server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: zjqzjq
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #exclusions: *.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: root
        allow:
        deny:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  messages:
    basename: i18n.login


#mybatis:
#  type-aliases-package:
#  configuration:
#    map-underscore-to-camel-case: true
#    use-generated-keys: true
